<?php if($this->isAllowed('form')): ?>	
	<div class="right"><?php echo $this->ajax("new", 'page/index/form/', 2); ?></div>
<?php endif; ?>	
<div class="left">
    <form id="formFindPage" action="#">
        <span class="ui-icon ui-icon-search magnifier"></span>
        <input type="text" name="q" id="qPage" style="width: 16em" />
        <input type="submit" value="ok" /> &nbsp;&nbsp;&nbsp;
    </form>
</div>
<div class="clear">&nbsp;</div>

<?php if (count($this->data)):?>
    <table class="datatable">
        <tr>
            <th><?php echo $this->translate('Order')?></th>
            <th><?php echo $this->translate('Name')?></th>
            <th><?php echo $this->translate('Status')?></th>
            <th></th>
        </tr>
        <?php foreach ($this->data as $key => $data): ?>
            <tr>
                <td><?php echo $data->position; ?></td>
                <td><?php echo $this->ajax($data->title, 'page/index/form/id/'. $data->id); ?></td>
                <td><?php echo $this->translate($data->status); ?></td>
                <td nowrap="nowrap">
                    <?php echo $this->ajax("delete", 'page/index/delete/id/' . $data->id, 2 , "want to delete?");?>
                </td>
            </tr>
        <?php endforeach;?>
    </table>
    <div id="page-page">
        <?php echo $this->paginationControl($this->data) ?>
    </div>
<?php else:?>
    <p><?php echo $this->translate( "there are no records" );?></p>
<?php endif;?>
<script type="text/javascript">
    $('.page-show').click(function(){
        $(this.target).toggle();
        return false;
    });

    $('#page-page a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });

    $("#formFindPage").submit(function(ev) {
		$(this).parents('.content').load('page/index/index/q/' + $('#qPage').val());
        return false;
	});

    $('input[type=button], input[type=submit]').button();
</script>